name: pilot_exam_app
description: "A new Flutter project."

publish_to: 'none' 

version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  flutter_riverpod: ^2.4.9
  fl_chart: ^0.65.0
  flutter_secure_storage: ^9.2.4
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  get_it: ^8.0.3
  injectable: ^2.5.0
  dartz: ^0.10.1
  flutter_hooks: ^0.21.2
  hooks_riverpod: ^2.6.1
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  injectable_generator: ^2.6.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/home.jpg
    - assets/images/auth background.jpg
    - assets/images/airplane.jpg
    - assets/images/interview.jpg
    - assets/images/resource.png

